//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelOwner()
        {
            this.Hotels = new HashSet<Hotel>();
        }
    
        public int Id { get; set; }
        public string HOwnerUsername { get; set; }
        public string HOwnerPassword { get; set; }
        public string HOwnerFirstName { get; set; }
        public string HOwnerLastName { get; set; }
        public string HOwnerEmail { get; set; }
        public string HOwnerContactNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotels { get; set; }
    }
}
